const GlobalIcons: any = {
  "icon-filter": "",
  "icon-compass":
    "/icons/svg/Base-blue/base-blue-compass.svg?updatedAt=1680783858784",
  "icon-compass-white":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base_icons/base-compass.svg?updatedAt=1680783662225",
  "icon-search":
    "/icons/svg/Base-blue/base-blue-search.svg?updatedAt=1680783899444",
  "icon-chat": "/icons/svg/Base-blue/base-blue-chat.svg",
  "icon-dashboard":
    "/icons/svg/Base-blue/base-blue-dashboard.svg?updatedAt=1685012312872",
  "icon-settings":
    "/icons/svg/Base-blue/base-blue-settingsFilled.svg?updatedAt=1680783904683",
  "icon-bell":
    "/icons/svg/Base-blue/base-blue-bell.svg?updatedAt=1685012312681",
  "icon-chat-white":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base_icons/base-chat.svg",
  "icon-mute-chat":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-volumeOff.svg?updatedAt=1680783916235",
  "icon-unmute-chat":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-volume.svg?updatedAt=1680783916154",
  "icon-select-chat":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-volume.svg?updatedAt=1680783916154",
  "icon-select":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-multiselect.svg?updatedAt=1680783884757",
  "icon-edit":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-edit.svg?updatedAt=1680783868992",
  "icon-photo":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-image.svg?updatedAt=1680783874121",
  "icon-video":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-volume.svg?updatedAt=1680783916154",
  "icon-file":
    "/icons/svg/Base-blue/base-blue-file.svg?updatedAt=1680783869110",
  "icon-pin":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-pinFilled.svg?updatedAt=1680783894226",
  "icon-wallet":
    "/icons/svg/Base-blue/base-blue-wallet.svg?updatedAt=1680783916158",
  "icon-poll":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-poll.svg?updatedAt=1680783894227",
  "icon-permissions":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-volume.svg?updatedAt=1680783916154",
  "icon-location":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-location.svg?updatedAt=1680783879376",
  "icon-clear-red":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Red_icons/base-red-cancel.svg?updatedAt=1683699287130",
  "icon-delete-red":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Red_icons/base-red-delete.svg?updatedAt=1683699287179",
  "icon-exit-red":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Red_icons/base-red-exit.svg?updatedAt=1683699740768",
  "icon-switch-profile":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-switchProfile.svg?updatedAt=1683788539413",
  "icon-call":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-volume.svg?updatedAt=1680783916154",
  "icon-device":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-volume.svg?updatedAt=1680783916154",
  "icon-notification":
    "/icons/svg/Base-blue/base-blue-volume.svg?updatedAt=1680783916154",
  "icon-notification-off":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-volume.svg?updatedAt=1680783916154",
  "icon-language":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-volume.svg?updatedAt=1680783916154",
  "icon-storage":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-volume.svg?updatedAt=1680783916154",
  "icon-contact":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-volume.svg?updatedAt=1680783916154",
  "icon-post":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-volume.svg?updatedAt=1680783916154",
  "icon-pay":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-volume.svg?updatedAt=1680783916154",
  "icon-block-red":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Red_icons/base-red-block.svg?updatedAt=1683699287123",
  "icon-chevron": "/icons/svg/Base-blue/base-blue-chevronBack.svg",
  "icon-chevron-next":
    "/icons/png/Base-blue_icons/base-blue-chevronNext.png?updatedAt=1680703639925",
  "icon-chevron-down": "/icons/svg/Base-blue/base-blue-chevronDown.svg",
  "icon-reply":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-replyFilled.svg",
  "icon-close": "/icons/svg/Base-blue/base-blue-cancel.svg",
  "icon-attachment":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-attachment.svg",
  "icon-send":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-send.svg",
  "icon-more":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-moreHorizontal.svg",
  "icon-unlike":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-unlike.svg",
  "icon-unlike-green":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Green_icons/green-unlike.svg",
  "icon-mirror-green":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Green_icons/green-mirror.svg",
  "icon-mirror":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-repeat.svg",
  "icon-collect-green":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Green_icons/green-collect.svg",
  "icon-collect":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-collect.svg",
  "icon-share":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-share-1.svg",
  "icon-forward":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-forward.svg?updatedAt=1680783869134",
  "icon-copy":
    "/icons/svg/Base-blue/base-blue-copy.svg?updatedAt=1680783864011",
  "icon-qr":
    "https://ik.imagekit.io/metaworkLabs/icons/png/Base-blue_icons/base-blue-qrCode.png?updatedAt=1683807162532",
  "icon-user":
    "/icons/png/Base-blue_icons/base-blue-user.png?updatedAt=1680703669687",
  "icon-connections":
    "https://ik.imagekit.io/metaworkLabs/icons/png/Base-blue_icons/base-blue-connections.png?updatedAt=1680788697983",
  "icon-chat-edit":
    "https://ik.imagekit.io/metaworkLabs/icons/svg/Base-blue/base-blue-editChat.svg",
};
export default GlobalIcons;
